[tool.black]
line-length = 135
target-version = ['py39']
skip-string-normalization = false
skip-magic-trailing-comma = false
exclude = '''
/(
    \.venv
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.hg
  | \.git
  | \.svn
  | \.ipynb_checkpoints
  | dist
  | build
  | __pycache__
)/
'''