FROM python:3.12.8-slim-bookworm

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libpq-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app

ADD app/requirements.txt .
RUN pip install -r requirements.txt

ADD app/ /app

RUN chmod +x /app/start.sh

EXPOSE 8080

CMD ["/app/start.sh"]